VirtusLab/besom

.github/workflows/upstream_proto.yml
scripts/Proto.scala

- token is required in CI
- token is optional locally

Update Proto script to be flexible regarding GH token

---

README.md
template/README.md

- fix typos
- add installation links for prerequisites
- update commands to reflect the actual `Justfile` commands
- add new lines for readability when reading markdown source

Update README files

---

.github/workflows/ci.yml
README.md

More info on how to setup for local develoment

Update README.md with IDE setup instructions

---

.gitignore
experimental/project.scala
template/default/Main.scala
template/default/project.scala
template/kubernetes/project.scala

Use compiler plugin in templates

---

.github/workflows/ci.yml
.github/workflows/test-website.yml
.github/workflows/website.yml

Allow only same repo PRs

---

core/src/main/scala/besom/types.scala

Better solution will be discussed in #144, solves #145

This is a temporary fix for #145

---

Justfile
scripts/Packages.scala

* Add script for building and publishing provider SDK modules in a batch mode
* Fix missing --power in publish

Publish improvements

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md
README.md
template/README.md

Update README, add CONTRIBUTING and CoC

---

README.md
website/docs/getting_started.md
website/docs/interpolator.md
website/docs/lifting.md
website/docs/tutorial.md

Fix typos, add minor improvements and corrections

Proofread docs

---

Justfile
examples/kubernetes-nginx/.gitignore
examples/kubernetes-nginx/Main.scala
examples/kubernetes-nginx/Pulumi.yaml
examples/kubernetes-nginx/README.md
examples/kubernetes-nginx/project.scala

Add the canonical k8s example.
Also fixes #155

Add kubernetes-nginx example

---

templates/aws/Main.scala
templates/default/Main.scala
templates/gcp/Main.scala
templates/gcp/Pulumi.yaml
templates/gcp/project.scala

Add GCP template

---

examples/aws-s3-folder/README.md
examples/aws-webserver/README.md
examples/gcp-static-page/.gitignore
examples/gcp-static-page/Main.scala
examples/gcp-static-page/Pulumi.yaml
examples/gcp-static-page/README.md
examples/gcp-static-page/project.scala

Add gcp-static-page example

---

core/src/main/scala/besom/internal/Engine.scala
core/src/main/scala/besom/internal/Monitor.scala
core/src/main/scala/besom/internal/netty.scala

Await for gRPC channel termination

---

CONTRIBUTING.md
Justfile

Run 'scala-cli setup-ide' for all modules with one command

Add mass-setup-ide to Justfile

---

.github/workflows/ci.yml
.github/workflows/examples.yml
.github/workflows/templates.yml
.github/workflows/test-website.yml

We seem to be ignoring branch pushes by accident. I hope this will solve the issue, if not we need to dig a little deeper into this.

Fix GH fork check

---

core/project.scala

- grpc-netty:1.45.0 -> 1.54.2
- fix multiple CVEs from guava and gson

Update gRPC dependencies

---

.github/workflows/test-website.yml
CONTRIBUTING.md
Justfile
README.md
website/docs/architecture.md
website/docs/basics.md
website/docs/components.md
website/docs/constructors.md
website/docs/context.md
website/docs/exports.md
website/docs/getting_started.md
website/docs/interpolator.md
website/docs/intro.md
website/docs/laziness.md
website/docs/lifting.md
website/docs/tutorial.md

Fix #221 - markdown snippets check with mdoc

---

.github/workflows/ci.yml
.github/workflows/examples.yml
.github/workflows/templates.yml

Update Pulumi in CI 3.86.0 -> 3.89.0

---

.github/workflows/ci.yml

- files will be fixed later, just list for now

Enable scalafmt with just `--list` param

---

core/src/main/scala/besom/internal/BesomModule.scala

- allow for deep debugging of integration between Pulumi Cli and lang-host and core

Log env vars with trace level

---

.github/workflows/ci.yml
.github/workflows/examples.yml
.github/workflows/templates.yml
.github/workflows/upstream_proto.yml
Justfile
integration-tests/CoreTests.test.scala
integration-tests/integration.scala
integration-tests/project.scala
integration-tests/resources/logger-example/project.scala

- base integration framework
- refactored core integration test
- updated test deps
- remove fetch-depth: 0 in workflows
Relates to: #237
Should be merged before #234 and #242

Improve core integration tests

---

.github/workflows/ci.yml
codegen/src/CodeGen.scala
core/src/main/scala/besom/internal/ResourceDecoder.scala
core/src/main/scala/besom/internal/codecs.scala
core/src/main/scala/besom/types.scala
core/src/test/scala/besom/internal/ContextTest.scala
core/src/test/scala/besom/internal/DecoderTest.scala
core/src/test/scala/besom/internal/EncoderTest.scala
core/src/test/scala/besom/internal/ValueAssertions.scala

Unmangle restricted field names in decoders, fix codecs for enums

---

Justfile
codegen/project.scala
codegen/resources/pulumi.json
integration-tests/resources/executors/sbt/build.sbt
scripts/Schemas.scala
scripts/common.scala

Update codegen part 1

---

Justfile
codegen/src/PulumiPluginJSON.scala
integration-tests/CodegenTests.test.scala
integration-tests/LanguagePluginTest.test.scala
integration-tests/integration.scala
integration-tests/project.scala

Taken from #258 
Based on #260 so it includes it

Codegen update part 2

---

Justfile
codegen/src/CodeGen.scala
codegen/src/Main.scala
codegen/src/SchemaProvider.scala
integration-tests/CodegenTests.test.scala
integration-tests/CoreTests.test.scala
integration-tests/LanguagePluginTest.test.scala
integration-tests/integration.scala
integration-tests/project.scala

- [Use codegen directly from tests](https://github.com/VirtusLab/besom/pull/263/commits/3dcf80caa79f937ea0655fd8aa0132e708baacbe)
- [Move test provider publishing to tests from Justfile](https://github.com/VirtusLab/besom/pull/263/commits/d944e2a9986be46950cceb0b5a7fda3254c02642)
Part of #257

Codegen update 4

---

codegen/src/ClassCoordinates.scala
codegen/src/ClassCoordinates.test.scala
codegen/src/CodeGen.scala
codegen/src/CodegenError.scala
codegen/src/Main.scala
codegen/src/PulumiPackage.scala
codegen/src/PulumiPackageInfo.scala
codegen/src/PulumiTypeCoordinates.scala
codegen/src/PulumiTypeCoordinates.test.scala
codegen/src/SchemaProvider.scala
codegen/src/TypeMapper.scala
codegen/src/TypeMapper.test.scala
codegen/src/Utils.scala
integration-tests/CoreTests.test.scala

Codegen changes:
- index module will be added when not provided by the schema (but also always removed from package name)
- dash-es will be removed from package and file path
- module parts will be split on `/` in packages and file path (there are schemas that do not provide correct module regexp)

Codegen update 6

---

codegen/src/ClassCoordinates.scala
codegen/src/CodeGen.scala
codegen/src/Config.scala
codegen/src/Logger.scala
codegen/src/Main.scala
codegen/src/PulumiPackage.scala
codegen/src/PulumiTypeCoordinates.scala
codegen/src/SchemaProvider.scala
codegen/src/UpickleApi.scala
codegen/src/Utils.scala
integration-tests/CodegenTests.test.scala

- update our metaschema model according to upstream JSON Schema (codegen/resources/pulumi.js)
- warn about parts of schema we ignore at the moment
- add kubernetes schema to codegen tests

Update PulumiPackage and warn about missing functionality

---

codegen/src/ClassCoordinates.scala
codegen/src/TypeMapper.test.scala
codegen/src/Utils.scala
integration-tests/CodegenTests.test.scala
integration-tests/resources/testdata/digitalocean.json
scripts/Schemas.scala

[Add digitalocean provider to tests](https://github.com/VirtusLab/besom/commit/7e342c85384fdaa188b072a18862903d78d777a9)

Codegen update - 8

---

codegen/src/PulumiPackage.scala
codegen/src/TypeMapper.scala
codegen/src/TypeMapper.test.scala
integration-tests/CodegenTests.test.scala

- [Enable schema tests that no longer fail](https://github.com/VirtusLab/besom/commit/28f781b8f3e95b73ea9e9157f89dfcdb2a1d0e4d)
- [Add AsScalaTypeTest regression test](https://github.com/VirtusLab/besom/commit/f15b8c2f9c2d97e02871022c6683e8205f6138f7)

Codegen update 10

---

scripts/Schemas.scala

- add plugin install before get-schema

Fix schema fetching

---

codegen/src/CodeGen.scala

Avoid name clashes with custom classes from schemas
* Don't use imports in generated code
* Extract some codegen helper logic

No imports in generated code

---

codegen/src/PulumiDefinitionCoordinates.test.scala
codegen/src/PulumiPackage.scala
codegen/src/SchemaProvider.scala
codegen/src/TypeMapper.test.scala
integration-tests/CodegenTests.test.scala

- Add codegen unit tests
- Simplify codegen integration tests
- update kubernetes schema

Update codegen tests

---

core/src/main/scala/besom/internal/codecs.scala
core/src/test/scala/besom/internal/DecoderTest.scala

- add unit test
- improve error message

Regression test for #148

---

website/docs/architecture.md
website/docs/basics.md
website/docs/constructors.md

A small website update inspired by #295

Update docs website

---

core/src/main/scala/besom/internal/BesomSyntax.scala
core/src/main/scala/besom/internal/Context.scala
core/src/main/scala/besom/internal/Env.scala
core/src/main/scala/besom/internal/Resource.scala
core/src/main/scala/besom/internal/RunInfo.scala
core/src/test/scala/besom/internal/DummyContext.scala
integration-tests/CoreTests.test.scala
integration-tests/resources/random-example/Main.scala

Add `pulumiResourceName` and `pulumiProject`, `pulumiOrganization`, `pulumiStack`

---

codegen/src/PulumiDefinitionCoordinates.scala
codegen/src/PulumiDefinitionCoordinates.test.scala
codegen/src/PulumiToken.scala
codegen/src/PulumiToken.test.scala

Fix provider coordinates vs token confusion

---

codegen/project.scala
core/project.scala
core/src/main/scala/besom/internal/Config.scala
core/src/main/scala/besom/internal/ConfigValueReader.scala
core/src/main/scala/besom/internal/Input.scala
core/src/main/scala/besom/internal/Output.scala
core/src/main/scala/besom/types.scala
core/src/test/scala/besom/internal/ConfigTest.scala
integration-tests/CoreTests.test.scala
integration-tests/integration.scala
integration-tests/resources/config-example/Main.scala

- add support for JSON configs, with AST and object results
- code and docs cleanup
Fixes #207

Add support for structural configs

---

codegen/src/PulumiPackage.test.scala
codegen/src/TypeMapper.test.scala

New unit test cases, some added as ignored as a reminder, related to #144

Add codegen unit test cases

---

.github/workflows/ci.yml
.github/workflows/examples.yml
.github/workflows/templates.yml
CONTRIBUTING.md
codegen/src/CodeGen.scala
codegen/src/CodeGen.test.scala
scripts/Packages.scala

- workaround https://github.com/pulumi/pulumi-kubernetes/issues/2683

Downgrade exception to logged error for id/urn property

---

codegen/src/CodeGen.scala
codegen/src/CodeGen.test.scala
codegen/src/Main.scala
codegen/src/PropertyInfo.scala
codegen/src/PulumiPackage.scala
codegen/src/TypeMapper.scala
codegen/src/Utils.scala
codegen/src/scalameta.scala
codegen/src/scalameta.test.scala
core/src/main/scala/besom/internal/codecs.scala
core/src/test/scala/besom/internal/DecoderTest.scala
integration-tests/CodegenTests.test.scala
scripts/Packages.scala

- add Decoder.discriminated in core
- use Decoder.discriminated in codegen
fixes #330

Add discriminated union decoders

---

examples/docker-multi-container-app/.gitignore
examples/docker-multi-container-app/README.md
examples/docker-multi-container-app/app/Main.scala
examples/docker-multi-container-app/app/project.scala
examples/docker-multi-container-app/infra/Main.scala
examples/docker-multi-container-app/infra/Pulumi.yaml
examples/docker-multi-container-app/infra/project.scala

Add docker-multi-container-app example

---

.github/workflows/ci.yml
.github/workflows/delete-old-packages.yaml
.github/workflows/examples.yml
.github/workflows/publish.yaml
.github/workflows/templates.yml
.github/workflows/upstream_proto.yml
CONTRIBUTING.md
Justfile
besom-json/project.scala
codegen/project.scala
codegen/src/CodeGen.scala
core/project.scala
scripts/Packages.scala
scripts/Schemas.scala
scripts/cli.scala
scripts/common.scala

Publishing update

---

CONTRIBUTING.md
Justfile
scripts/Packages.scala
scripts/Proto.scala
scripts/Version.scala
scripts/cli.scala

Updates and fixes for our internal scripts - working towards low cost releases and maintenance

Update Besom scripts

---

codegen/src/CodeGen.scala
codegen/src/CodeGen.test.scala
codegen/src/PulumiPackage.scala

I've updated our codegen TODOs, alse added comment in #77

Cleanup codegen TODOs

---

core/src/main/scala/besom/internal/codecs.scala

- SpecialResourceSig instead of SpecialSecretSig

Fix resource decoders

---

CONTRIBUTING.md
examples/gcp-cloudrun/.gitignore
examples/gcp-cloudrun/README.md
examples/gcp-cloudrun/app/.dockerignore
examples/gcp-cloudrun/app/Dockerfile
examples/gcp-cloudrun/app/Main.scala
examples/gcp-cloudrun/app/project.scala
examples/gcp-cloudrun/infra/Main.scala
examples/gcp-cloudrun/infra/Pulumi.yaml
examples/gcp-cloudrun/infra/project.scala

Ported https://github.com/pulumi/examples/tree/master/gcp-ts-cloudrun

Add GCP Cloud Run example

---

CONTRIBUTING.md
codegen/src/CodeGen.scala
codegen/src/PropertyInfo.scala
codegen/src/TypeMapper.scala
codegen/src/TypeMapper.test.scala
core/src/main/scala/besom/internal/Config.scala
core/src/main/scala/besom/types.scala
core/src/test/scala/besom/internal/CodegenTest.scala
core/src/test/scala/besom/internal/ConfigTest.scala
scripts/Packages.scala
scripts/Version.scala
scripts/common.scala

- Fix missing JsonFormat for PulumiAny
- Fix multi-line @deprecated argument in codegen
- Mangle property names in codegen with reserved package names
- Fix codegen type unescaping method
- Fix codegen type mapper for malformed named types with not leading slash
new Packages scripts functionality

Fix codegen

---

CONTRIBUTING.md
Justfile
website/README.md
website/docs/api_reference.md
website/docs/basics.md
website/docs/constructors.md
website/docs/getting_started.md
website/docs/intro.md
website/docs/logging.md
website/docs/tutorial.md
website/src/remark/codeblockVersion.js

- fix right sidebar in basics page
- minor editing corrections
- update release instructions

Update website, Justfile and CONTRIBUTING.md

---

examples/aws-s3-folder/project.scala
examples/aws-secrets-manager/project.scala
examples/aws-webserver/project.scala
templates/aws/project.scala

Update our examples and templates to the latest versions from the Pulumi Repository.

Update providers in examples and templates

---

website/docs/basics.md

ups, we've included this in the changelog but forgot the actual docs

Add missing documentation on StackReference

---

experimental/project.scala
experimental/src/main/scala/besom/liftoff.scala

- make liftoff destroy cleanly (it removes PVs correctly)
- use more variables to showcase best practices 
- expose LoadBalancer (works also on Docker Desktop)

Liftoff update/fix

---

experimental/project.scala
experimental/src/main/scala/besom/liftoff.scala

Fix liftoff after Component API changes

Fix liftoff example

---

examples/gcp-gke/.gitignore
examples/gcp-gke/Main.scala
examples/gcp-gke/Pulumi.yaml
examples/gcp-gke/README.md
examples/gcp-gke/project.scala

https://github.com/pulumi/examples/blob/master/gcp-ts-gke-hello-world/README.md

Add GKE cluster example

---

examples/azure-static-website/.gitignore
examples/azure-static-website/Main.scala
examples/azure-static-website/Pulumi.yaml
examples/azure-static-website/README.md
examples/azure-static-website/project.scala
examples/azure-static-website/wwwroot/404.html
examples/azure-static-website/wwwroot/index.html

https://github.com/pulumi/examples/tree/master/azure-ts-static-website

Add Azure static website example

---

website/docs/changelog.md

Updated changelog for 0.3.1 with correction

---

examples/aws-webserver/Pulumi.yaml
examples/aws-wordpress-fargate-rds/Backend.scala
examples/aws-wordpress-fargate-rds/Frontent.scala
examples/aws-wordpress-fargate-rds/Main.scala
examples/aws-wordpress-fargate-rds/Network.scala
examples/aws-wordpress-fargate-rds/Pulumi.yaml
examples/aws-wordpress-fargate-rds/README.md
examples/aws-wordpress-fargate-rds/project.scala

https://github.com/pulumi/examples/tree/master/aws-ts-wordpress-fargate-rds

Add Wordpress Fargate RDS example

---

examples/kubernetes-yaml-crd/.gitignore
examples/kubernetes-yaml-crd/Main.scala
examples/kubernetes-yaml-crd/Pulumi.yaml
examples/kubernetes-yaml-crd/README.md
examples/kubernetes-yaml-crd/project.scala

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

Add Kubernetes YAML with CRD example

---

.github/workflows/ci.yml
language-plugin/pulumi-language-scala/executors/executor_scala_cli.go

add BESOM_LANGHOST_SCALA_CLI_OPTS env var handling to scala-cli langhost executor

Allow passing options to scala-cli via language plugin executor

---

examples/gcp-functions/.gitignore
examples/gcp-functions/Main.scala
examples/gcp-functions/Pulumi.yaml
examples/gcp-functions/README.md
examples/gcp-functions/project.scala

https://github.com/pulumi/examples/tree/master/gcp-ts-functions

Add GCP Functions example

---

examples/gcp-instance-nginx/.gitignore
examples/gcp-instance-nginx/Main.scala
examples/gcp-instance-nginx/Pulumi.yaml
examples/gcp-instance-nginx/README.md
examples/gcp-instance-nginx/project.scala

https://github.com/pulumi/examples/tree/master/gcp-py-instance-nginx

Add GCP Instance NGINX example

---

examples/aws-redshift-glue-etl/.gitignore
examples/aws-redshift-glue-etl/Main.scala
examples/aws-redshift-glue-etl/Pulumi.yaml
examples/aws-redshift-glue-etl/README.md
examples/aws-redshift-glue-etl/events-1.txt
examples/aws-redshift-glue-etl/glue-job.py
examples/aws-redshift-glue-etl/project.scala

https://github.com/pulumi/examples/tree/master/aws-ts-redshift-glue-etl

An ETL pipeline with Amazon Redshift and AWS Glue example

---

scripts/project.scala

scripts for 0.3.2 were published for jdk 21 because of lack of this line :|

fix target java version for scripts package
