- .github/workflows/ci.yml
- Justfile
- codegen/project.scala
- codegen/src/CodeGen.scala
- codegen/src/Main.scala
- codegen/src/PulumiPackage.scala
- language-plugin/bootstrap/project.scala
- language-plugin/pulumi-language-scala/executors/executor_sbt.go
- language-plugin/pulumi-language-scala/main.go
- language-plugin/tests/resources/executors/sbt/build.sbt
- language-plugin/tests/resources/executors/sbt/src/main/scala/Main.scala
- language-plugin/tests/resources/executors/scala-cli/Main.scala
- language-plugin/tests/resources/executors/scala-cli/project.scala
- language-plugin/tests/resources/fake-external-resource-plugin/Lib.scala
- language-plugin/tests/resources/fake-external-resource-plugin/resources/besom/api/fake-external-resource/plugin.json
- language-plugin/tests/resources/fake-standard-resource-plugin/Lib.scala
- language-plugin/tests/resources/fake-standard-resource-plugin/resources/besom/api/fake-standard-resource/plugin.json
- language-plugin/tests/src/LanguagePluginExecutorTest.scala
* Expose plugiDownloadURL from provider schemas to plugin.json to make community packages automatically installable
* Avoid clashes on plugin.json resources
* Enable building language plugin for different platforms
> Fix resource plugin auto-setup

- website/docs/lifting.md
I don't see `url` being used, so my hunch is that this is a leftover from the past that isn't being compile-time checked.
> Fix possible mistake in lifting docs

- website/.gitignore
- website/docs/architecture.md
- website/docs/basics.md
- website/docs/components.md
- website/docs/constructors.md
- website/docs/context.md
- website/docs/exports.md
- website/docs/interpolator.md
- website/docs/intro.md
- website/docs/laziness.md
- website/docs/lifting.md
- website/docs/missing.md
- website/docs/tutorial.md
- website/package.json
- website/sidebars.js
- added Basics page
- improved linking between pages
- minor improvements to most of the pages
- missing.md update
- address #211
> Update docs website

- README.md
- website/docs/getting_started.md
Thanks to scala CLI team we have now a pretty install url :)
Fixed here:
https://github.com/VirtusLab/scala-cli/issues/2427
As we say in Poland: "a small thing but it makes me happy"
> Use shorter scala-cli install one-liner

- Justfile
- codegen/src/CodeGen.scala
- codegen/src/PulumiTypeCoordinates.scala
- codegen/src/TypeMapper.scala
- codegen/src/TypeMapper.test.scala
- codegen/src/Utils.scala
- integration-tests/CodegenTests.test.scala
- [Codegen disallows empty module in Pulumi type](https://github.com/VirtusLab/besom/commit/5b13046fb78e56d726c6f34e574019190d31da64)
- [Add ensureIndexModule to codegen config for optional sanitization](https://github.com/VirtusLab/besom/commit/334208db0e1fd271e64daf62ba6a4c35456eeaa2)
- [Add TypeToken in codegen](https://github.com/VirtusLab/besom/commit/04240276bc816e03c019b239af006bafb1272aee)
other small fixes
> Codegen - deal with broken schemas

- CONTRIBUTING.md
- Justfile
- codegen/src/CodeGen.scala
- codegen/src/Config.scala
- codegen/src/Main.scala
- codegen/src/PulumiDefinitionCoordinates.test.scala
- codegen/src/PulumiPackage.test.scala
- codegen/src/PulumiToken.scala
- codegen/src/TypeMapper.scala
- codegen/src/TypeMapper.test.scala
- codegen/src/Utils.scala
- compiler-plugin/project.scala
- integration-tests/CodegenTests.test.scala
- integration-tests/integration.scala
- language-plugin/bootstrap/project.scala
- scripts/Packages.scala
> Codegen - fix tests

- core/src/main/scala/besom/internal/BesomModule.scala
- core/src/main/scala/besom/internal/Context.scala
Context was closing gRPC due to older implementation and therefore breaking the ordering guarantees by Result.resource.
> fixes #228

- core/src/main/scala/besom/future.scala
- core/src/main/scala/besom/internal/BesomModule.scala
- core/src/main/scala/besom/internal/BesomSyntax.scala
- core/src/main/scala/besom/internal/Config.scala
- core/src/main/scala/besom/internal/ConfigValueReader.scala
- core/src/main/scala/besom/internal/Env.scala
- core/src/main/scala/besom/internal/Output.scala
- core/src/main/scala/besom/internal/Resource.scala
- core/src/main/scala/besom/internal/errors.scala
- core/src/main/scala/besom/types.scala
- core/src/main/scala/besom/util/NonEmptyString.scala
- core/src/test/scala/besom/internal/ConfigTest.scala
- integration-tests/CoreTests.test.scala
- integration-tests/integration.scala
- integration-tests/resources/config-example/Main.scala
- integration-tests/resources/config-example/Pulumi.yaml
- integration-tests/resources/config-example/project.scala
- finishing touches on #287 to improve `Config` ergonomy
- add `Output[Option[A]].orElse` and `.getOrElse`
- add unit tests, integration tests, scaladoc
Fixes #204
Fixes #205
> Test and document Config

- CONTRIBUTING.md
- Justfile
- codegen/src/CodeGen.scala
- codegen/src/CodeGen.test.scala
- codegen/src/Logger.scala
- codegen/src/Main.scala
- codegen/src/PropertyInfo.scala
- codegen/src/PropertyInfo.test.scala
- codegen/src/PulumiDefinitionCoordinates.scala
- codegen/src/PulumiDefinitionCoordinates.test.scala
- codegen/src/PulumiPackageInfo.scala
- codegen/src/ScalaDefinitionCoordinates.scala
- codegen/src/ScalaDefinitionCoordinates.test.scala
- codegen/src/SchemaProvider.scala
- codegen/src/TypeMapper.scala
- codegen/src/TypeMapper.test.scala
- codegen/src/Utils.scala
- integration-tests/CodegenTests.test.scala
- integration-tests/integration.scala
- scripts/Packages.scala
- fix method generation
- don't generate `__self__` properties on methods
- normalize type names to consistent CameCase, .e.g. IPAddress -> IpAddress
- add a space between method names ending witn underscore and the colon
- fix enum param default values - lookup instance by value in gen-time
> Update codegen - normalize type names, fix methods

- codegen/src/PropertyInfo.test.scala
- codegen/src/PulumiDefinitionCoordinates.scala
- codegen/src/ScalaDefinitionCoordinates.scala
- codegen/src/TypeMapper.scala
The assumption here is that we'll never propagate `Args` suffix to nested resource types.
Based on https://github.com/pulumi/pulumi/blob/16d9f4c1670404c2cb2f15d2dd095f05dc8eec12/pkg/codegen/nodejs/gen.go#L295
Fixes #144
> Disallow nested arg Resource types in codegen's TypeMapper

- README.md
- website/docs/examples.md
- website/docs/getting_started.md
- website/docs/templates.md
This gives us two benefits:
- stable links in docs that correspond to release
- ability to continuously update examples and templates and use them as DX/regresssion tests
> Use tagged link for examples and templates

- codegen/src/CodeGen.scala
- codegen/src/CodeGen.test.scala
- core/project.scala
- core/src/main/scala/besom/aliases.scala
- core/src/main/scala/besom/internal/BesomSyntax.scala
- core/src/main/scala/besom/internal/Context.scala
- core/src/main/scala/besom/internal/CustomTimeouts.scala
- core/src/main/scala/besom/internal/Input.scala
- core/src/main/scala/besom/internal/Resource.scala
- core/src/main/scala/besom/internal/ResourceOps.scala
- core/src/main/scala/besom/internal/ResourceOptions.scala
- core/src/main/scala/besom/internal/ResourceState.scala
- core/src/main/scala/besom/internal/StackReference.scala
- core/src/main/scala/besom/internal/codecs.scala
- core/src/main/scala/besom/internal/resources.scala
- core/src/test/scala/besom/external/ResourceConstructorTest.scala.scala
- core/src/test/scala/besom/internal/OutputTest.scala
- core/src/test/scala/besom/internal/RunOutput.scala
- examples/aws-s3-folder/Main.scala
- examples/docker-multi-container-app/infra/Main.scala
- experimental/src/main/scala/besom/liftoff.scala
- website/docs/constructors.md
- website/docs/tutorial.md
> Overhauled ResourceOptions and implemented Remote Components

- core/src/main/scala/besom/internal/Output.scala
- core/src/test/scala/besom/internal/OutputTest.scala
uh, Iterable instead of IterableOnce, thanks Scala Collections!
> Fix traverse on Output

- core/src/main/scala/besom/future.scala
- core/src/main/scala/besom/internal/BesomModule.scala
this crashes the app if a fatal error is encountered (instead of hanging as Future does) because NonFatal().
> Fix fatals hanging the app with FutureRuntime

- core/src/main/scala/besom/internal/ResourceOps.scala
- core/src/main/scala/besom/internal/resources.scala
- core/src/test/scala/besom/internal/ResourceOpsTest.scala
as in the title, we have had our impl from Java impl which was ported from C# impl which is broken and includes custom resource children of any other resources, including local, remote components and other custom resources, this works and is covered with an extensive test
> fix transitive dependency resolution algorithm

- core/src/main/scala/besom/types.scala
- core/src/test/scala/besom/util/URNTest.scala
- allow for a dot in the URN's module part
fixes #384
> Fix URL validation to allow for kubernetes types

- core/src/main/scala/besom/internal/Context.scala
- examples/kubernetes-guestbook/components/Main.scala
- examples/kubernetes-guestbook/simple/Main.scala
that was a dumb mistake really, copilot / copy-paste based prolly
Public / user-facing component API does not take any *Args so to reuse the internal functions it uses EmptyArgs with it's ArgsEncoder instance, this was copy-pasted in the rush of implementing remote components when RemoteComponents do actually take Args. The change is not binary-incompatible, just a patch version release should be enough.
> Fix issue 397

- core/src/main/scala/besom/aliases.scala
- core/src/main/scala/besom/internal/CustomTimeouts.scala
I've noticed we lack non-internal alias for CustomTimeout we've added recently, this change adds and along with basic scaladoc.
> Add alias and docs for custom timeouts

- codegen/src/CodegenError.scala
- core/src/main/scala/besom/internal/codecs.scala
- core/src/main/scala/besom/util/Validated.scala
- core/src/test/scala/besom/internal/EncoderTest.scala
- preserve cause and all other causes
Example:
```scala
val errors = NonEmptyVector(
DecodingError("error1", label = Label.fromNameAndType("dummy1", "dummy:pkg:Dummy1"), cause = Exception("cause1")),
DecodingError("error2", label = Label.fromNameAndType("dummy2", "dummy:pkg:Dummy1")),
DecodingError("error3", label = Label.fromNameAndType("dummy3", "dummy:pkg:Dummy1"))
)
val aggregated = AggregatedDecodingError(errors)
```
```
besom.internal.AggregatedDecodingError: Decoding Errors [3]:
error1
error2
error3
(with aggregate stack trace)
at besom.internal.AggregatedDecodingError$.apply(codecs.scala:100)
at besom.internal.InternalTest.$init$$$anonfun$34(EncoderTest.scala:996)
at munit.internal.console.StackTraces$.dropOutside(StackTraces.scala:12)
...
at …
```
> Fix AggregateException

- core/src/main/scala/besom/internal/Context.scala
- core/src/main/scala/besom/internal/Memo.scala
- core/src/main/scala/besom/internal/ResourceDecoder.scala
- core/src/main/scala/besom/internal/ResourceOps.scala
- core/src/main/scala/besom/internal/ResourceOptions.scala
- core/src/main/scala/besom/internal/Result.scala
- core/src/main/scala/besom/internal/resources.scala
- core/src/test/scala/besom/internal/DummyContext.scala
- core/src/test/scala/besom/internal/MemoTest.scala
- core/src/test/scala/besom/internal/ResourceDecoderTest.scala
- experimental/src/main/scala/besom/liftoff.scala
- integration-tests/CoreTests.test.scala
- integration-tests/resources/memoization/source-stack/Main.scala
- integration-tests/resources/memoization/source-stack/Pulumi.yaml
- integration-tests/resources/memoization/source-stack/project.scala
- integration-tests/resources/memoization/target-stack/Main.scala
- integration-tests/resources/memoization/target-stack/Pulumi.yaml
- integration-tests/resources/memoization/target-stack/project.scala
Final solution for memo issues.
> Memoization of pulumi side effects

- besom-json/src/main/scala/besom/json/JsonFormat.scala
- besom-json/src/main/scala/besom/json/ProductFormats.scala
- besom-json/src/main/scala/besom/json/package.scala
- besom-json/src/test/scala/besom/json/DerivedFormatsSpec.scala
- besom-json/src/test/scala/besom/json/ProductFormatsSpec.scala
- core/src/main/scala/besom/internal/Env.scala
- core/src/main/scala/besom/json/custom/interpolator.scala
- core/src/main/scala/besom/json/interpolator.scala
- core/src/main/scala/besom/util/JsonInterpolator.scala
- core/src/test/scala/besom/internal/ConfigTest.scala
- core/src/test/scala/besom/util/CompileAssertions.scala
- core/src/test/scala/besom/util/JsonInterpolatorTest.scala
- integration-tests/resources/config-example/Main.scala
- website/docs/changelog.md
- website/docs/json.md
- website/docusaurus.config.js
- website/sidebars.js
* Adds `import besom.json.default.*` to allow easy use of derivation without `given JsonProtocol = DefaultJsonProtocol`
* Adds `json""` interpolator that verifies json correctness in compile time and interpolates Outputs like `pulumi""` interpolator
* besom.json handles default args correctly now (if a field is missing in json and constructor has a default argument for that field, default value will be used) 
Still needs: changes in examples and a JSON section in docs.
BREAKS BINCOMPAT ON besom.json !!! Release as next minor.
> Json handling improvements

- core/src/main/scala/besom/internal/Output.scala
- core/src/test/scala/besom/internal/OutputTest.scala
fixes https://github.com/VirtusLab/besom/issues/435
> Add `Output.when`

- core/src/main/scala/besom/internal/Output.scala
- core/src/main/scala/besom/internal/Result.scala
- core/src/test/scala/besom/internal/OutputTest.scala
Adds nice compile error for wrong usage of flatMap and for missing instance of Result.ToFuture
> Improve errors around `Output.eval` and `Output#flatMap` / `ToFuture` `@implicitNotFound`

- core/src/main/scala/besom/internal/Output.scala
- core/src/test/scala/besom/internal/OutputTest.scala
> Add lifts to `Output[Option[List[A]]]` etc.

- codegen/src/CodeGen.scala
- codegen/src/CodeGen.test.scala
- codegen/src/Config.scala
- codegen/src/DefinitionCoordinates.test.scala
- codegen/src/Logger.scala
- codegen/src/Main.scala
- codegen/src/Overlay.scala
- codegen/src/PackageMetadata.test.scala
- codegen/src/PropertyInfo.test.scala
- codegen/src/PulumiDefinitionCoordinates.scala
- codegen/src/PulumiDefinitionCoordinates.test.scala
- codegen/src/PulumiPackageInfo.scala
- codegen/src/PulumiToken.scala
- codegen/src/ScalaDefinitionCoordinates.scala
- codegen/src/ScalaDefinitionCoordinates.test.scala
- codegen/src/SchemaProvider.scala
- codegen/src/TypeMapper.scala
- codegen/src/TypeMapper.test.scala
- codegen/src/Utils.scala
- integration-tests/CoreTests.test.scala
- integration-tests/integration.scala
- scripts/Packages.scala
- refactor codegen to allow for the required changes to be made
- `implicit val` changed to `given`/`using`
- unified `Config` with added overlays dir setting (`overlaysDir`/`DefaultOverlaysDir`)
- pre-process the schema and store parsed types, resources and functions in `PulumiPackageInfo`
- store a reference to the deserialized schema in the `PulumiPackageInfo`
- store provider related config (e.g. overlays) per schema in the `PulumiPackageInfo`
- parsing logic moved from `SchemaProvider` and `PulumiPackageOps` to `PulumiPackageInfo`
- other small cosmetic changes, renames, etc
- add support for overlays in codegen (`Overlay.scala`)
fixes #286 (was closed as done, but we were just ignoring the overlays, now we can add them)
> Add overlay support to codegen

- core/src/main/scala/besom/util/NonEmptyString.scala
- core/src/test/scala/besom/util/CompileAssertions.scala
- core/src/test/scala/besom/util/NonEmptyStringTest.scala
pulumi string interpolation inference macro threw MatchError on dynamic Output[String]
> fix issue 462 - MatchError in Output[String] -> Output[NonEmptyString] inference

- core/project.scala
- core/src/main/scala/besom/internal/Output.scala
- core/src/main/scala/besom/internal/OutputUnzip.scala
- core/src/test/scala/besom/internal/OutputTest.scala
- website/docs/changelog.md
some discussion regarding destructuring in for-comprehensions is still to be had @pawelprazak
> add more combinators to Output - issue #466

- examples/azure-webserver/.gitignore
- examples/azure-webserver/Main.scala
- examples/azure-webserver/Pulumi.yaml
- examples/azure-webserver/README.md
- examples/azure-webserver/project.scala
https://github.com/pulumi/examples/tree/master/azure-ts-webserver
> Add Azure webserver example

- codegen/src/CodeGen.test.scala
- codegen/src/PropertyInfo.scala
- core/src/main/scala/besom/internal/codecs.scala
- core/src/test/scala/besom/internal/ResourceDecoderTest.scala
I believe we have to wait for `0.4.0` for this one to be on the safe side since we are changing the core, unless we can prove this is not a braking change for the `0.3.x` line.
Fixes #458
> Update mangled properties list

- core/src/main/scala/besom/internal/Resource.scala
- core/src/main/scala/besom/internal/ResourceState.scala
- core/src/main/scala/besom/internal/resources.scala
This fixes problem with missing `ResourceState` for components due to `A <: ComponentResource` / `ComponentBase` split (`Resources` keeps instances of `ComponentBase` as keys, user can provide `A <: ComponentResource` as lookup value). Solved by exposing internally the `ComponentBase` dependency in any `A <: ComponentResource` and using it as lookup value in `Resources`.
> fix issue 488

- codegen/src/CodeGen.scala
- codegen/src/Config.scala
- codegen/src/Main.scala
At the moment publishing settings for generated sources are hard-coded to besom specific values. However if a developer of a pulumi provider wants to add a first-party support for besom and publish the generated sdk by themselves, they would want to configure these values.
This PR proposes a way to override the publishing settings via cli arguments
> Allow overriding publishing settings for codegen

- codegen/src/CodeGen.scala
- codegen/src/CodeGen.test.scala
- codegen/src/Utils.scala
> WithArgs (copy) method added to args companion object

- besom-cfg/k8s/project.scala
- core/src/main/scala/besom/internal/ResourceAlias.scala
- core/src/main/scala/besom/internal/ResourceOps.scala
- core/src/main/scala/besom/internal/ResourceOptions.scala
- integration-tests/CoreTests.test.scala
- integration-tests/resources/random-example/Main.scala
Introduces support for pulumi aliases: https://www.pulumi.com/docs/concepts/options/aliases/
Tested on aws-eks example and random package.
> Aliases support

- Justfile
- besom-cfg/k8s/project.scala
- core/src/main/scala/besom/internal/Output.scala
- examples/azure-aci/.gitignore
- examples/azure-aci/Main.scala
- examples/azure-aci/Pulumi.yaml
- examples/azure-aci/README.md
- examples/azure-aci/project.scala
- scripts/Packages.scala
- scripts/common.scala
https://github.com/pulumi/examples/tree/master/azure-ts-aci
> Add Azure ACI example

- examples/azure-cosmosdb-logicapp/.gitignore
- examples/azure-cosmosdb-logicapp/Main.scala
- examples/azure-cosmosdb-logicapp/Pulumi.yaml
- examples/azure-cosmosdb-logicapp/README.md
- examples/azure-cosmosdb-logicapp/project.scala
https://github.com/pulumi/examples/tree/master/azure-ts-cosmosdb-logicapp
Wait until https://github.com/VirtusLab/besom/issues/521 is done
> An example of azure-cosmosdb-logicapp

- examples/azure-synapse/.gitignore
- examples/azure-synapse/Main.scala
- examples/azure-synapse/Pulumi.yaml
- examples/azure-synapse/README.md
- examples/azure-synapse/project.scala
https://github.com/pulumi/examples/tree/master/azure-ts-synapse
> Add Azure Synapse Workspace and Pools example

- Justfile
- integration-tests/LanguagePluginTest.test.scala
- language-plugin/bootstrap/PulumiPlugins.scala
- language-plugin/bootstrap/project.scala
- language-plugin/pulumi-language-scala/executors/executor.go
- language-plugin/pulumi-language-scala/executors/executor_gradle.go
- language-plugin/pulumi-language-scala/executors/executor_jar.go
- language-plugin/pulumi-language-scala/executors/executor_maven.go
- language-plugin/pulumi-language-scala/executors/executor_sbt.go
- language-plugin/pulumi-language-scala/executors/executor_scala_cli.go
- language-plugin/pulumi-language-scala/main.go
Build tools might add some garbage to stdout while running the plugin discoverer.
Printing the result's json into a file should solve this problem and make plugins discovery more reliable.
Also bumping pulumi version used in CI
> Pass plugin discoverer output via a temp file
